// Auto-generated by test_cov. Do not edit by hand.

import 'future_middleware_test.dart' as future_middleware_test;
import 'future_reducer/success_reducer_test.dart' as future_reducer_success_reducer_test;
import 'future_reducer/with_custom_defaults_test.dart' as future_reducer_with_custom_defaults_test;
import 'future_reducer/with_custom_reducers_test.dart' as future_reducer_with_custom_reducers_test;
import 'future_reducer/with_defaults_test.dart' as future_reducer_with_defaults_test;
import 'future_reducer/with_defaults_without_future_state_test.dart' as future_reducer_with_defaults_without_future_state_test;

void main() {
  future_reducer_success_reducer_test.main();
  future_reducer_with_defaults_without_future_state_test.main();
  future_reducer_with_custom_reducers_test.main();
  future_reducer_with_custom_defaults_test.main();
  future_reducer_with_defaults_test.main();
  future_middleware_test.main();
}
