container:
  image: cirrusci/flutter:latest

style_task:
  test_style_script:
    - dartfmt --set-exit-if-changed lib

test_task:
  env:
    CODECOV_TOKEN: ENCRYPTED[1f01d1491a4355b42e57b0a9ae467e0db04510125470fed3b0a1e68c2ed468d1d7ae83b763aa03b591d92ba0385ffc86]
  pub_cache:
    folder: ~/.pub-cache
  test_script:
    - pub get
    - pub run test_coverage
  codecov_script:
    - echo $CODECOV_TOKEN
    - bash <(curl -s https://codecov.io/bash) -t f95f59bf-3434-45e6-aada-b3db5d04d8d3
