container:
  image: cirrusci/flutter:latest

style_task:
  test_style_script:
    - dartfmt --set-exit-if-changed lib

test_task:
  env:
    CODECOV_TOKEN: ENCRYPTED[1f01d1491a4355b42e57b0a9ae467e0db04510125470fed3b0a1e68c2ed468d1d7ae83b763aa03b591d92ba0385ffc86]
  pub_cache:
    folder: ~/.pub-cache
  test_script:
    - pub get
    - pub run test test/redux_future_test.dart
    - pub get --packages-dir
    - pub global activate coverage
    - pub global run coverage:collect_coverage --port=8111 -o coverage.json --resume-isolates --wait-paused &
    - dart --observe=8111 test/redux_future_test.dart
    - pub global run coverage:format_coverage --package-root=packages --report-on lib --in coverage.json --out lcov.info --lcov
  codecov_script:
    - bash <(curl -s https://codecov.io/bash) -t $CODE_COV_TOKEN
