name: redux_future_middleware
description: >
  A Middleware for Redux which makes handling Dart Future easy by using Actions.
version: 0.4.1
homepage: https://github.com/shbmbhrdwj/redux_future
repository: https://github.com/shbmbhrdwj/redux_future
issue_tracker: https://github.com/shbmbhrdwj/redux_future/issues/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  redux: ^5.0.0

dev_dependencies:
  test: ^1.16.8
  test_cov: ^1.0.1
  pedantic: ^1.11.0
