name: redux_future_middleware
description: A new Flutter package project.
version: 0.0.1
author: Shubham Bhardwaj <shbmbhrdwj@gmail.com>
homepage: https://github.com/shbmbhrdwj/redux_future
repository: https://github.com/flrx/validator
issue_tracker: https://github.com/flrx/validator/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.6
  redux: ^3.0.0

dev_dependencies:
  test: ^1.9.4
  test_coverage: ^0.4.0
